### ISSUE TITLE
[null]what's this?

### ISSUE THREAD

**Issue by nenekodev** [ITRClub/Calendar#2]
探班

**Comment by SmallOyster** [comment]
约会专用……

用户可以把有事的日子输进日历里，然后自动显示有空的日子并生成照片，用户就可以分享出去，别人就知道什么时候可以约你了。

灵感 From 月事日历表(?) 我记得好像是 😂 😂 😂

**Comment by nenekodev** [comment]
不错

**Comment by SmallOyster** [comment]
@df7c5117

等你过完这个学期一不一起来搞啊[勾引]

话说挺谢谢你那么关注我的 :joy: ，新建了个org你就来了

**Comment by nenekodev** [comment]
行啊 反正我挖了那么多坑没填

**Comment by SmallOyster** [comment]
呃呃呃呃呃呃

**Comment by nenekodev** [comment]
哦提醒一下，itrclub的服务器启用https后友言评论就无法使用了 因为chrome会自动block掉https站点的非https跨站连接

解决方法的话，可以参考这个 https://segmentfault.com/a/1190000004200361

**Comment by SmallOyster** [comment]
yes……校运会那儿已经删了……

谢谢给的解决方案！
